name: Keep Render API Alive

on:
  schedule:
    - cron: "*/5 * * * *" # Chạy mỗi 5 phút
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s https://dev-class-server-nodejs.onrender.com/api/products
