name: Keep Render API Alive

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          echo "Pinging API..."
          curl -I https://dev-class-server-nodejs.onrender.com
