name: Keep Render API Alive

on:
  schedule:
    - cron: "*/14 * * * *" # chạy mỗi 14 phút
  workflow_dispatch: # vẫn cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          curl -s https://dev-class-server-nodejs.onrender.com > /dev/null
